### ISSUE TITLE
Work Journey

### ISSUE THREAD

**Issue by Bruno-Lira** [Bruno-Lira/oORG#1]
- [ ] Clock

- [ ] Config a timer for work in a day

- [ ] Return the timer with visual graphic

- [ ] Create a alert when the timer finish

**Comment by Bruno-Lira** [comment]
**Calendar**

- [ ] Show the day

- [ ] Show the calendar

- [ ] Save the daily tasks

- [ ] Import the google calendar tasks

**Comment by Bruno-Lira** [comment]
**To-Do List**

- [ ] Can add a task

- [ ] Can mark and unmark the task as finished

- [ ] Mark a day for tasks
